

exports.sinistresData = [
  {
    "id": 4408,
    "etat": "recu",
    "chauffeurEmail": null,
    "creatorRole": "super_admin",
    "creatorId": "1",
    "createdAt": "2023-05-04T00:35:32.111Z",
    "updatedAt": "2023-05-04T00:35:32.111Z",
    "constat": null,
    "permis_conduire": null,
    "carte_grise": null,
    "declaration_chauffeur": null,
    "autres_pieces": null,
    "declarationSinistre": {
      "NUMERO_CLIENT": "4",
      "DOSSIER": 4408,
      "DOSSIER_CLIENT": null,
      "ANNEE": "2020",
      "ASSUREUR": "AXA",
      "NUMERO_CONTRAT": "10433437204",
      "AMIABLE": null,
      "REF_SINISTRE_ASUREUR": "8537768873",
      "DATE_RECEPTION": "07-09-2020",
      "DATE_SURVENANCE": "23-06-2020",
      "HEURE": "Entre_6h_9h",
      "CAS": "Arret",
      "LIEU_SINISTRE": null,
      "REGION": null,
      "SOCIETE": "ANTONIN 1919",
      "SITE": null,
      "TYPE_VEHICULE": null,
      "IMMATRICULATION": "FH-194-FH",
      "MARQUE": "FORD",
      "PREMIERE_MEC": "24-06-2019",
      "PERTE_FI": null,
      "CONDUCTEUR": "PIVIDORI CLAIRE",
      "POURCENTAGE_RC": "0",
      "CAS_IDA": null,
      "NATURE": null,
      "CIRCONSTANCE": "Notre assuré se fait percuter à l'Arret en stationnement",
      "DOMMAGES": null,
      "DOMMAGES_SAISIE8_LIBRE": null,
      "ASSUREUR_ADV": "GAN",
      "CONVENTION": null,
      "FRANCHISE": null,
      "MONTANT_DOM": null,
      "DATE_MISSIONNEMENT": null,
      "LIEU_EXPERTISE": null,
      "DATE_EXPERTISE": null,
      "DATE_PRE_RAPPORT": null,
      "REF_EXPERTISE": null,
      "DATE_RAPPORT_DEFINITIF": null,
      "COUT_EXPERT": null,
      "REPARATION": null,
      "CESSION_EPAVE": null,
      "MONTANT_RECOURS": null,
      "PIECES_MANQUANTES": null,
      "DETAIL_PIECES_MANQUANTES": null,
      "DATE_RELANCE_PIECES_MANQUANTES": null,
      "CONSTAT_ORIGINAL": null,
      "DATE_CLOTURE": "17-03-2021",
      "CHARGE_PROVISIONNELLE_ASSUREUR": null,
      "CHARGE_REELLE": "-1320.27",
      "ETAT": "Clos",
      "CHARGE_AJUSTEE": null,
      "COMMENTAIRES": "expertise regroupée avec le sinistre du 31/08  même véhicule réglé le 21/01/21 157,73"
    }
  },
  // {
  //   "id": 4409,
  //   "etat": "recu",
  //   "chauffeurEmail": null,
  //   "creatorRole": "super_admin",
  //   "creatorId": "1",
  //   "createdAt": "2023-05-04T00:35:32.111Z",
  //   "updatedAt": "2023-05-04T00:35:32.111Z",
  //   "constat": null,
  //   "permis_conduire": null,
  //   "carte_grise": null,
  //   "declaration_chauffeur": null,
  //   "autres_pieces": null,
  //   "declarationSinistre": {
  //     "NUMERO_CLIENT": "4",
  //     "DOSSIER": 4409,
  //     "DOSSIER_CLIENT": null,
  //     "ANNEE": "2022",
  //     "ASSUREUR": "AXA",
  //     "NUMERO_CONTRAT": "10433437204",
  //     "AMIABLE": null,
  //     "REF_SINISTRE_ASUREUR": "11724882773",
  //     "DATE_RECEPTION": "28-06-2022",
  //     "DATE_SURVENANCE": "23-06-2022",
  //     "HEURE": "Entre_22h_3h",
  //     "CAS": "En_Circulation",
  //     "LIEU_SINISTRE": "A62  AIGUILLON",
  //     "REGION": null,
  //     "SOCIETE": "FROMAFRUIT EPL LUCMARET",
  //     "SITE": null,
  //     "TYPE_VEHICULE": "TRR",
  //     "IMMATRICULATION": "GE-864-HD",
  //     "MARQUE": "RENAULT",
  //     "PREMIERE_MEC": "25-01-2022",
  //     "PERTE_FI": null,
  //     "CONDUCTEUR": "LARROUDE TONY",
  //     "POURCENTAGE_RC": "100",
  //     "CAS_IDA": null,
  //     "NATURE": null,
  //     "CIRCONSTANCE": "Notre assuré s'est fait doublé par la droite sur une voix de travaux par un vehicule tiers qui lui a projeté un panneau de signalisation",
  //     "DOMMAGES": null,
  //     "DOMMAGES_SAISIE8_LIBRE": null,
  //     "ASSUREUR_ADV": null,
  //     "CONVENTION": "non",
  //     "FRANCHISE": "1000",
  //     "MONTANT_DOM": null,
  //     "DATE_MISSIONNEMENT": null,
  //     "LIEU_EXPERTISE": null,
  //     "DATE_EXPERTISE": null,
  //     "DATE_PRE_RAPPORT": null,
  //     "REF_EXPERTISE": null,
  //     "DATE_RAPPORT_DEFINITIF": null,
  //     "COUT_EXPERT": null,
  //     "REPARATION": null,
  //     "CESSION_EPAVE": null,
  //     "MONTANT_RECOURS": null,
  //     "PIECES_MANQUANTES": null,
  //     "DETAIL_PIECES_MANQUANTES": null,
  //     "DATE_RELANCE_PIECES_MANQUANTES": null,
  //     "CONSTAT_ORIGINAL": null,
  //     "DATE_CLOTURE": null,
  //     "CHARGE_PROVISIONNELLE_ASSUREUR": null,
  //     "CHARGE_REELLE": "5297.09",
  //     "ETAT": "En cours",
  //     "CHARGE_AJUSTEE": null,
  //     "COMMENTAIRES": "EXPERTISE DEMANDEE Pré rapport 6020,61€ ATTENDONS FACTURE Relance pour facture le 24.01.23 Facture ok. A REGLER L'ENSEMBLE ROUTIER 5108,61€"
  //   }
  // },
]

exports.usersData = [
  // {
  //   "id": 5,
  //   "email": "aymen.agrebi.dev@gmail.com",
  //   "nom": "aymen",
  //   "prenom": "agrebi",
  //   "mdp": "$2b$10$yXfXCwIQKP9pJRdkgdNGjePmMQ2Ja7N9PBGnDvMWl/WMos8hyeUYq",
  //   "role": "client_admin",
  //   "numTel": "27424712",
  //   "resetLink": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJheW1lbi5hZ3JlYmkuZGV2QGdtYWlsLmNvbSIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJleHBpcmVzSW4iOjM2MDAwLCJpYXQiOjE2ODc2OTY1OTV9.Fac1QY1VJOIt3wI8tLcfs0HXltokP6AzBzSy5wHP_-4",
  //   "aciveInactive": true,
  //   "profile": null
  // },
  {
    "id": 7,
    "email": "olivier.domejean.agt@axa.fr",
    "nom": "Domejean",
    "prenom": "Olivier",
    "mdp": "$2b$10$CbNCTjpaETOEohjAG3HTvuluNF4IQdbX3f9yj56LF2Eu44JlelrZq",
    "role": "client_admin",
    "numTel": "+33685842456",
    "resetLink": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJvbGl2aWVyLmRvbWVqZWFuLmFndEBheGEuZnIiLCJyb2xlIjoiY2xpZW50X2FkbWluIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNjg3ODQ3Mjc3fQ.rN31pGEnK18ZJJtE98RncHJHjWh5deUGNMfCD96TaUs",
    "aciveInactive": true,
    "profile": null
  },
  {
    "id": 8,
    "email": "helene.brie@primever.com",
    "nom": "Brie",
    "prenom": "Hélène",
    "mdp": "$2b$10$pcbSLugdhlZZO3z/dk614.tKVlzGuFsjURIhhaJ6ic0yRZYGIH4Qi",
    "role": "client_admin",
    "numTel": "052438020",
    "resetLink": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJoZWxlbmUuYnJpZUBwcmltZXZlci5jb20iLCJyb2xlIjoiY2xpZW50X2FkbWluIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNjgzMTg4MTU1fQ.I3eCB3iMvMwN2KXk9H1JzAPTvD5pZQ7XU2rgih2Ree4",
    "profile": null,
  },
]

exports.adminsData = [
  {
    "id": 7,
    "email": "olivier.domejean.agt@axa.fr",
    "nom": "Domejean",
    "prenom": "Olivier",
    "mdp": "$2b$10$CbNCTjpaETOEohjAG3HTvuluNF4IQdbX3f9yj56LF2Eu44JlelrZq",
    "role": "client_admin",
    "numTel": "+33685842456",
    "resetLink": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiZW1haWwiOiJvbGl2aWVyLmRvbWVqZWFuLmFndEBheGEuZnIiLCJyb2xlIjoiY2xpZW50X2FkbWluIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNjg3ODQ3Mjc3fQ.rN31pGEnK18ZJJtE98RncHJHjWh5deUGNMfCD96TaUs",
    "aciveInactive": true,
    "userId": 22,
    "clientID": 1
  },
  {
    "id": 8,
    "email": "helene.brie@primever.com",
    "nom": "Brie",
    "prenom": "Hélène",
    "mdp": "$2b$10$pcbSLugdhlZZO3z/dk614.tKVlzGuFsjURIhhaJ6ic0yRZYGIH4Qi",
    "role": "client_admin",
    "numTel": "052438020",
    "resetLink": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiZW1haWwiOiJoZWxlbmUuYnJpZUBwcmltZXZlci5jb20iLCJyb2xlIjoiY2xpZW50X2FkbWluIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNjgzMTg4MTU1fQ.I3eCB3iMvMwN2KXk9H1JzAPTvD5pZQ7XU2rgih2Ree4",
    "aciveInactive": true,
    "userId": 21,
    "clientID": 2
  },
]

exports.managersData=[
  {
    "id": 13,
    "userId": 24,
    "clientId": 1,
    "droits": null
  }
]