###
GET http://localhost:5001/api/fleetrisk/clients

###
POST  http://localhost:5004/fleetrisk/dashbord
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsImVtYWlsIjoiYXBpLmFkbWluQGZsZWV0cmlzay5mciIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJleHBpcmVzSW4iOjM2MDAwLCJpYXQiOjE3MDg2NDQ1MjR9.CxTAWMDETVGybD3Mhs2p77EdbsafVBOBOunCa8drdBY


{
    "annee": "2023",
    "region": null,
    "societe": null,
    "site": null
}

###
POST http://localhost:5004/users/add
Content-Type: application/json

{
    "user": {
        "email": "api.admin@fleetrisk.fr",
        "nom": "fleetrisk",
        "prenom": "api admin",
        "role": "client_admin",
        "mdp": "Mcxl.kj5dd.sqd!"
    }
}

###
POST http://localhost:5004/users/login
Content-Type: application/json

{
    "email": "api.admin@fleetrisk.fr",
    "mdp": "Mcxl.kj5dd.sqd!"
}

###
POST http://dashboard.fleetrisk.fr/users/add
Content-Type: application/json

{
    "user": {
        "email": "api.admin@fleetrisk.fr",
        "nom": "fleetrisk",
        "prenom": "api admin",
        "role": "client_admin",
        "mdp": "Mcxl.kj5dd.sqd!"
    }
}

###
POST http://dashboard.fleetrisk.fr/users/login
Content-Type: application/json

{
    "email": "api.admin@fleetrisk.fr",
    "mdp": "Mcxl.kj5dd.sqd!"
}


###
GET http://dashboard.fleetrisk.fr/users

###
POST  http://dashboard.fleetrisk.fr/fleetrisk/dashbord
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsImVtYWlsIjoiYXBpLmFkbWluQGZsZWV0cmlzay5mciIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJleHBpcmVzSW4iOjM2MDAwLCJpYXQiOjE3MDg2NDQ1MjR9.CxTAWMDETVGybD3Mhs2p77EdbsafVBOBOunCa8drdBY


{
    "annee": "2023",
    "region": null,
    "societe": null,
    "site": null
}
GET https://dashboard.fleetrisk.fr/users