###
DELETE https://dashboard.fleetrisk.fr/users/69


###
POST https://dashboard.fleetrisk.fr/users/add
Content-Type: application/json

{
    "user": {
        "email": "api.admin@fleetrisk.fr",
        "nom": "fleetrisk",
        "prenom": "api admin",
        "role": "client_admin",
        "mdp": "Mcxl.kj5dd.sqd!"
    }
}

###
POST https://dashboard.fleetrisk.fr/users/login
Content-Type: application/json

{
    "email": "api.admin@fleetrisk.fr",
    "mdp": "Mcxl.kj5dd.sqd!"
}


###
POST  https://dashboard.fleetrisk.fr/dashbord
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsImVtYWlsIjoiYXBpLmFkbWluQGZsZWV0cmlzay5mciIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJpYXQiOjE3MDg2NTM5MzAsImV4cCI6MTczNzQ1MzkzMH0.EjzbE5_fOEDa7nZ9A8Nyp3Sdlwiq4eDB06Sd8mnaJV0


{
    "annee": "2023",
    "region": null,
    "societe": null,
    "site": null
}

###
POST http://localhost:5004/users/login
Content-Type: application/json

{
    "email": "api.admin@fleetrisk.fr",
    "mdp": "Mcxl.kj5dd.sqd!"
}

###
POST  http://localhost:5004/user/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsImVtYWlsIjoiYXBpLmFkbWluQGZsZWV0cmlzay5mciIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJpYXQiOjE3MDg2NTMxMTgsImV4cCI6MTczNzQ1MzExOH0.CkPs0pitr2umKPjKOt5fpeC3nMgzcB-eVmlq_e_0ZTM"
}


###
GET https://dashboard.fleetrisk.fr/users

###
# Authorization: bearer seyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsImVtYWlsIjoiYXBpLmFkbWluQGZsZWV0cmlzay5mciIsInJvbGUiOiJjbGllbnRfYWRtaW4iLCJleHBpcmVzSW4iOjM2MDAwLCJpYXQiOjE3MDg2NDQ1MjR9.CxTAWMDETVGybD3Mhs2p77EdbsafVBOBOunCa8drdBY