
GET http://localhost:5000/api/users

###
POST http://51.83.77.61/api/users/add
Content-Type: application/json

{
  "email": "super.admin@mail.com",
  "nom": "super",
  "prenom": "admin",
  "mdp": "polm1213",
  "role": "super_admin"
}

###
GET http://localhost:5000/api/clients
###
DElETE http://localhost:5000/api/clients/1

###
POST http://51.83.77.61/api/clients/add
Content-Type: application/json

{
    "nomClient": "aaaa",
    "email": "contact@gggg.fr",
    "numTel": "555201228",
    "adresse": "2500 dsfdfsd ds",
    "nomDomaine": "@primever.fr",
    "numSiret": "12345671234567",
    "isActive": true,
    "donneesCrypte": false,
    "descriptifAssistance": "dsfdsfds dsf ds dsf fds dsfdsf dsfdsfds dsf ds dsf fds dsfdsf dsfdsfds dsf ds dsf fds dsfdsf",
    "startDate": "2023-01-15",
    "endDate": "2023-12-30",
    "superAdminID": 1
}

### contrat
GET http://localhost:5000/api/clients/contrats/2
###

DElETE http://localhost:5000/api/clients/contrats/4

###
POST http://localhost:5000/api/clients/contrats
Content-Type: application/json

{
    "ClientID": 2,
    "refContrat": "ffffff",
    "Assureur": "fdg",
    "typeContrat": "dfds",
    "startDate": "2022-12-02",
    "endDate": "2022-12-31"
}



###
PUT http://localhost:5000/api/clients/:id
Content-Type: application/json

{
    "nomClient": "pix",
    "email": "ommmjp@pppo.fdfd",
    "numTel": 565563365,
    "adresse": "2500 fsdf",
    "nomDomaine": "@ddffd.dfsd",
    "numSiret": "12345671234567",
    "donneesCrypte": false,
    "descriptifAssistance": "dsfd dfsd  ds df dfdfdsfds dsd dsfd dfsd  ds df dfdfdsfds dsd",
    "startDate": "2023-01-15",
    "endDate": "2023-12-09",
    "superAdminID": 1
}
###

GET http://localhost:5000/api/sinistres

###

DELETE http://localhost:5000/api/sinistres/7

###
POST http://51.83.77.61/api/sinistres/add
Content-Type: application/json

{
  "sinistre" : {
    "creatorId": "1",
    "creatorRole": "super_admin"
  },
  "decSinistre" :{
    "Cie_adv" : "sdfsdf",
    "NumClient" : "",
    "Conducteur" : "dsfds",
    "Date_Survenance" : "2022-12-10",
    "Date_recep" : "2022-12-03",
    "Immatriculation" : "dsfdsf",
    "LIEU_SINISTRE" : "dfsdf",
    "premiere_MEC" : "dsqdqs",
    "Type_Vehicule" : "SR"
  }
}



###
  #  "Annee": 2022,
  #   "DossierClient" : "2",
  #   "NumClient": "1",
  #   "ASSUREUR": "assureur",
  #   "numContart": "6556",
  #   "Amiable": "oui",
  #   "ref_Sinistre": "15658545",
  #   "Date_recep": "2022-12-16",
  #   "Date_Survenance": "2022-12-05",
  #   "Heure": "Entre_11h_13h",
  #   "CAS": "Arret",
  #   "LIEU_SINISTRE": "BORDEAUX LAC",
  #   "SOCIETE_A_Facturer": "STSO",
  #   "Site": "SAMAZAN", 
  #   "Region": "Sud-Ouest",
  #   "Type_Vehicule": "TRR",
  #   "Immatriculation": "FF-933-SP",
  #   "Marque": "RENAULT",
  #   "premiere_MEC": "2018-12-16",
  #   "Perte_Fi": "oui",
  #   "Conducteur": "FETEGUE CISSE",
  #   "pourcentage_RC": 100,
  #   "Cas_IDA": 40,
  #   "Nature": "Non_Auto",
  #   "Circonstances": "Notre assuré a percuté le poteau et le porche du magasin AUCHAN LAC",
  #   "Dommages": "LATERAL DROIT",
  #   "Cie_adv": "MMA",
  #   "Conv": "oui",
  #   "Mt_Dom": 950.2,
  #   "Franchise": 0,
  #   "Date_MISSIONNEMENT": "11-01-2022",
  #   "Lieu_expertise": "VOLVO SELVA SAMAZAN",
  #   "Date_EXPERTISE"            :"11-01-2022",
  #   "Date_RAPPORT"             :"11-01-2022",
  #   "Ref_expertise": 32565656,
  #   "Date_RAPPORT_DEFINITIF"   :"11-01-2022",
  #   "cout_expert": 208.5,
  #   "REPARATION_oui_non": "oui",
  #   "CESSION_EPAVE": "non",
  #   "Mt_rec": 150,
  #   "Pieces_manquantes_Oui_Non": "oui",
  #   "Detail_pieces_manquantes": "DC",
  #   "Date_de_relance_pieces_M":"17-03-2022",
  #   "Constat_original_O_N": "oui",
  #   "Date_clot": "05-09-2022",
  #   "Charge_Provisionnelle_Solaris": 107.4,
  #   "Charge_ajustee": 255.2,
  #   "Charge_reelle": 202.75,
  #   "Etat": "En_cours",
  #   "Commentaires": "Expertise demandée PRE RAPPORT RENDU DDE FCATURE à Alexandrine REG FAIT"