const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()

exports.getSites = async(req, res, next) => {
    const sites=[
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
        {  id: 1,
           name: 'nom du site',
           email: 'contact@site.fr',
           numTel: '+33 1 23 45 67 89',
            adresse:  'adresse du site',
            creerPar:     'super_admin',
            isActive:    true,
            societe:      'nom du societe',
        },
    ]
    return res.status(200).json(sites)
}